[build]
  publish = "."
  command = "# no build command"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/quiz"
  to = "/quiz.html"
  status = 200
